---
title: "La qualité des données dans les sources de données"
subtitle: "Jour 1"
author: "Karim Mezhoud"
institute: "CNSTN"
date: "2023/12/12"
output:
  slidy_presentation: default
  logo: logo.jpg
  beamer_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Jour 1 \| Introduction à la qualité des données

-   Titre : La qualité des données dans les sources de données

-   Introduction : Expliquer l'importance de la qualité des données dans les sources de données

# Jour 1 \| Définir la qualité

-   Qu'est-ce que la qualité des données ?

-   Définir la qualité des données et ses dimensions principales : précision, exhaustivité, cohérence, actualité, unicité, etc.

# Jour 1 \| Importance de la Qualité des données

-   Pourquoi la qualité des données est-elle importante ?

-   Présenter les conséquences d'une mauvaise qualité des données : prises de décision erronées, pertes financières, inefficacité opérationnelle, atteinte à la réputation, etc.



# Jour 1 \| Les sources des données:

- Sources de données courantes

- Enumérer les différentes sources de données couramment utilisées : bases de données, fichiers CSV, API, médias sociaux, capteurs, etc.
